### ISSUE TITLE
naming issue of property key 'HUSID'

### ISSUE THREAD

**Issue by willblenkhorn** [jiscdev/analytics-udd#271]
Hi everyone,

Currently there is a slight naming issue with the UDD property key 'HUSID' (in Github). When data is downloaded from the LDH the UDD property key is 'HUS_ID'. I feel that either the name of the github field needs to change to reflect the name in the LDH or the LDH needs to change to the github naming convention.

Regards,

Will

**Comment by alanepaull** [comment]
It's HUSID in HESA, standing for "HESA unique student identifier". I wasn't aware that it was different in the Learning Data Hub when downloaded. As this property has historically always been HUSID (pronounced "Hewsid", I believe, and not "Huss ID"), I think it would be confusing to use HUS_ID anywhere.

Proposal: check and amend occurrences of HUS_ID to HUSID in any UDD context.

**Comment by ryansmith94** [comment]
Hi guys, we were actually made aware of this a couple of months ago and we believe we fixed it. What endpoint are you using to access the UDD?

**Comment by willblenkhorn** [comment]
That sounds great thanks.

**Comment by ht2** [comment]
Sorry Will, not sure if you missed @ryansmith94's question; can we double check the URL you are using on the UDD, or if you know it, the UDD version?

**Comment by willblenkhorn** [comment]
Hi James, I've just sent you an email with the details. Thanks.

**Comment by willblenkhorn** [comment]
Thanks for your help James, seems I was looking at old data sorry (hangs head in shame). Problem solved.
